name: 'size-limit-action'
description: 'size-limit action'
author: 'Andres Alvarez <a.alvarez.sor@gmail.com>'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  directory:
    required: false
    description: "a custom subdirectory"
  script:
    required: false
    default: "npx size-limit --json"
    description: "The script used to generate size-limit results"
  runner_temp:
    required: true
    description: 'temporary running directory with check-size directory'
runs:
  using: 'node16'
  main: 'dist/index.js'
